name: Run dummy test case
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:  
  run_fmu_dummy:
    name: Run FMU dummy
    runs-on: ubuntu-latest
    container: precice/precice
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2      

      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3-pip git python-is-python3 pkg-config
          python -m pip install --upgrade pip
          pip install fmpy

      - name: Install fmiprecice
        run: pip3 install --user .

      - name: Run coupling of two FMU dummies
        timeout-minutes: 3
        run: |
          cd tests/
          bash SolverOne/run.sh & bash SolverTwo/run.sh

      - name: Check the result
        timeout-minutes: 3
        run: |
          cd tests/
          python3 test.py
